### ISSUE TITLE
Config file doesn't have the right path on non-Windows platforms

### ISSUE THREAD

**Issue by sargunv** [Draylar/vanilla-hammers#1]
![image](https://user-images.githubusercontent.com/1320357/55864029-88038280-5b30-11e9-9a47-b4569b829fbe.png)

You'll notice the vanilla_hammers directory is empty and the actual config file generated with the name `vanilla_hammers\vanilla_hammers.json`. Looks like you've hardcoded the `\` in the path, instead of using the File/Path methods that handle non-Windows platforms properly.

**Comment by Draylar** [comment]
Should be fixed in 1.1.0. Thanks for the report!
