### ISSUE TITLE
License Change

### ISSUE THREAD

**Issue by Draylar** [Draylar/vanilla-hammers#101]
I'm looking to change the license of Vanilla Hammers from [GPLv3](https://github.com/Draylar/vanilla-hammers/blob/1.17/LICENSE) to [MIT](https://opensource.org/licenses/MIT). GPLv3 is a restrictive license that mandates forks use the same license (as well as a few other things), while MIT is fairly free and does not impose major restrictions on forks.

Everyone below has code or contributions present in this repository. Please let me know if you have any qualms about the license change, or reply with an okay if you are fine with it.

**Translators:**
- [x] @02David03
- [x] @qsefthuopq
- [ ] @mindy15963
- [x] @TheDirectorX
- [x] @doctor4t
- [ ] @XuyuEre
- [x] @200542053
- [x] @YanisBft
- [ ] @pandory-network 

**Code Contributors:**
- [ ] @Cyphrags
- [ ] @Bulldog83
- [x] @LemmaEOF 
- [ ] @Levoment 
- [x] @Linguardium 

Once you have commented, I would recommend unsubscribing on the right-hand bar so you do not receive further notifications:

![image](https://user-images.githubusercontent.com/17728338/132953582-0485f069-d849-415e-b996-96a46bd9a147.png)

Thank you!

**Comment by YanisBft** [comment]
I agree with the change

**Comment by LemmaEOF** [comment]
Go ahead!

**Comment by Linguardium** [comment]
Sounds good!

**Comment by 02David03** [comment]
I'm okay with the change

Em sáb., 11 de set. de 2021 17:22, Linguardium ***@***.***>
escreveu:

**Comment by doctor4t** [comment]
OK, no problem!

**Comment by TheDirectorX** [comment]
https://github.com/MelanX/MoreVanillaTools/issues/28#issuecomment-922494947

**Comment by James103** [comment]
If you want to be more formal, use the following template:

> I, [your GitHub username], agree to Vanilla Hammers being relicensed under the MIT license.

**Comment by qsefthuopq** [comment]
It's okay. And you can merge the update request from another translator.

**Comment by Draylar** [comment]
I'll be going through with the relicense to MIT with the removal of contributions currently licensed under GPLv3 by authors who have not consented to the relicense. Current contributors who have _not_ agreed to the relicense and their contributions include:
- mindy15963 - ko_kr translation, removed
- XuyuEre - Chinese translations, removed
- pandory-network - German translations, removed
- Bulldog83 - version changes, extended hitbox rendering changes (no longer in Vanilla Hammers)
- Cyphrags - version changes & Fabric Example Mod update
- Levoment - recipe advancements (going to remove & clean room re-add later)

I just re-wrote the versioning file and copied over the default Fabric Example Mod buildscript template. **_This means the latest commits in the 1.18 branch are now exclusively composed of code written by myself and contributors who have agreed to the MIT relicense._** If you have any qualms/concerns with this, please let me know and we can find a solution.

As always, previous releases - which is anything before 3.2.0 for 1.18 - are still licensed to downloaders under the GPLv3 license (& you'll find source archives on all public Vanilla Hammer distributions to abide with GPLv3 rules).

To those who contributed translations that are being removed in 1.18, please let me know if you agree to the relicense from GPLv3 to MIT and I will re-add the files. I appreciate everyone's cooperation!

**Comment by Levoment** [comment]
I approve. What I contributed to the wiki is outdated, but I approve.
