### ISSUE TITLE
Hammers create a ton of extra rare materials

### ISSUE THREAD

**Issue by lesseroftwogoods** [Draylar/vanilla-hammers#104]
Every time I use a hammer to hit a mob or break a block (or in a hammers case 9 blocks) it generates 9 entities of the material the hammer is made of. My diamond hammer generates 9 extra diamond entities every time I use it and same with my obsidian one. The free resources are kinda cool but it also takes a lot of the fun out of looking and working for stuff. Also it makes my inventory a mess with extra blocks. Any idea if this is getting fixed or maybe it's intentional and I missed that somehow? Right now it's making me not want to use the hammers as much.

**Comment by Draylar** [comment]
This is a feature of the Forge port of Vanilla Hammers ([CF](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers-forge) - [GitHub](https://github.com/MelanX/vanilla-hammers)), which I am unaffiliated with. I would recommend asking on their GitHub tracker instead. 🎃
