### ISSUE TITLE
No Config and tons of useless hammers.

### ISSUE THREAD

**Issue by StoneLegion** [Draylar/vanilla-hammers#109]
I installed Vanilla Hammers and I got a buttload of extra hammers and there is no config to disable anything or any config I can find.

I'm not sure if there is an error or not as it does not Match the Curse Page description.

Thanks.

**Comment by Draylar** [comment]
Logs, please! Vanilla Hammers has a config file named `vanilla-hammers.json` in your config folder. The second line in this config file, `enableExtraMaterials`, is what you are looking for.
