### ISSUE TITLE
1.14.3 (crash on load)vanilla-hammers-1.4.0

### ISSUE THREAD

**Issue by SDUBZ** [Draylar/vanilla-hammers#11]
crash:
https://github.com/thebrightspark/SparksHammers/files/3331687/crash-2019-06-27_05.49.26-client.txt

log:
https://github.com/thebrightspark/SparksHammers/files/3331690/latest.log

**Comment by Draylar** [comment]
This was fixed in 1.4.1; you're on 1.4.0.
1.4.2 was just released if you are planning on playing 1.14.3, so you may want to skip to that.
Thanks for the report!
