### ISSUE TITLE
1.18.2 Compatibility Please.

### ISSUE THREAD

**Issue by simonjonnemeth** [Draylar/vanilla-hammers#112]
Come on. All my other mods have been updated already,

**Comment by Ayutac** [comment]
Be a bit more respectful to devs that give you mods for free, yes?

**Comment by Draylar** [comment]
> Come on. All my other mods have been updated already,

Welcome to the life of a mod developer, everybody! For the rest of you - thanks for your patience, Vanilla Hammers is out on 1.18.2 now. Let me know if you have any issues. I'll be looking into updating Vanilla Excavator soon as well!
