### ISSUE TITLE
Hammer with silk touch problem

### ISSUE THREAD

**Issue by calloatti** [Draylar/vanilla-hammers#16]
I am using https://www.curseforge.com/minecraft/mc-mods/silky-spawners with vanilla hammers

Silky-Spawners-1.0.2
vanilla-hammers-1.4.3
MC 1.14.3

A pick with silk drops a spawner when I break a spawner

A hammer with silk does NOT drop a spawner when I break a spawner.

https://github.com/NerdHubMC/Silky-Spawners/issues/2

**Comment by Draylar** [comment]
Should be fixed in the latest update, as I've changed the breaking methods used by hammers.
