### ISSUE TITLE
Cant seem to get it working on my server

### ISSUE THREAD

**Issue by Vekkish** [Draylar/vanilla-hammers#19]
I add the vanilla-hammers-1.4.1 for version 1.14.2 and I can see the hammers and give myself a hammer when i go to use it it digs a 3x3 area like it should but when i try to move forward it only actually only dug 1x1 and i have to place blocks to get the blocks to reappear so I can dig them out again if i open a chest or anything after giving myself a hammer it disappears

**Comment by Vekkish** [comment]
![my mod folder](https://user-images.githubusercontent.com/54047204/63220665-9f93ed00-c15a-11e9-8f0b-117316797033.png)

**Comment by Vekkish** [comment]
![my mod folder](https://user-images.githubusercontent.com/54047204/63220714-5f813a00-c15b-11e9-9db3-808f7b19ca9b.png)

**Comment by Draylar** [comment]
Sorry for the late response.
If the hammers are disappearing out of your inventory, it's most likely a Fabric issue. Ghost blocks should be fixed in 1.6+.
