### ISSUE TITLE
Dynagear Copper Hammer takes Cobalt Blocks for some reason 

### ISSUE THREAD

**Issue by Bluberry-Kat** [Draylar/vanilla-hammers#20]
![image](https://user-images.githubusercontent.com/20749209/63901705-cb716700-c9d3-11e9-84ab-f5ce71e66a33.png)
and to confirm it's not just REI: 
![image](https://user-images.githubusercontent.com/20749209/63901726-e217be00-c9d3-11e9-8dcb-f031b1e0ed74.png)

using vanilla-hammers 1.6.1
dynagear 1.3.1+1.14.4
cotton resources 1.4.0+1.14.4
fabric loader v0.6.1+build.164
fabric api v0.3.2+build.216-1.14

all of the recipes besides the copper hammer are correct
unsure if this problem is on this mod's side or on dynagear's side, will post the issue over there if requested

**Comment by Draylar** [comment]
Yeah, dynagear was probably incorrectly configured for this hammer. I'll talk to Boundary about it, thanks!
