### ISSUE TITLE
Strange behavior around fluids

### ISSUE THREAD

**Issue by dranorter** [Draylar/vanilla-hammers#21]
When I use the hammer through running water, it removes the wrong blocks. The block I actually target always gets removed, but the eight surrounding blocks don't, or sometimes two or three of them will. Sometimes I will unexpectedly mine blocks which are under me or behind me. The hammer can end up removing blocks which are diagonally removed from the targeted block in all three dimensions, or blocks which are perhaps two blocks distant in one dimension.

Experimenting a bit, I'm pretty sure of what's going on. When I target a block through a fluid, the hammer's "adjacent" blocks end up being the eight blocks surrounding whatever fluid block I'm directly looking at. So, usually this will be the blocks surrounding the fluid block directly above the block I'm actually targeting, but by looking through fluid at different angles I can "target" different fluid blocks and therefore break different "adjacent" blocks.

**Comment by Draylar** [comment]
Thanks for the report! Will be fixed in 1.6.2.
