### ISSUE TITLE
Minecraft crashes when settings opened

### ISSUE THREAD

**Issue by appuchias** [Draylar/vanilla-hammers#22]

**Comment by Draylar** [comment]
Hi appuchias, thanks for the report.
Auto Config was designed for Cloth Config 1, but Cloth Config 2 is the norm now. Unfortunately, AC hasn't updated for the latter, which means the config screen will crash.
My two options are using a new config system or waiting for sargunv to update AC. I'll check if he plans on updating today, and look into switching systems if needed.
