### ISSUE TITLE
[Feature request] Lumber axes

### ISSUE THREAD

**Issue by KokSaker** [Draylar/vanilla-hammers#25]
The hammers and the excavators are wonderfully made. The lumber axes that could chop down a whole tree would be a good addition to this series. Thank you.

**Comment by Levoment** [comment]
I second this. I would love to see an axe that can chop down whole trees. I know the chopping algorithm would need to be non-recursive. That way, even if a tree is composed of 100 thousand logs, it could be chopped down without causing a StackOverflowError. A queue is perfect for the task.

**Comment by Draylar** [comment]
Great ideas! Going to mark this down for the future.
