### ISSUE TITLE
[1.14.4 - fabric] how can i repair

### ISSUE THREAD

**Issue by Atomkraftzwerg1** [Draylar/vanilla-hammers#29]
How can i repair my lapiz hammer?
with lapiz or lapiz blocks it doesnt work ont the anvil

thx for any help
Steve

**Comment by MelanX** [comment]
https://github.com/Draylar/vanilla-hammers/blob/master/src/main/java/com/github/draylar/vh/common/HammerMaterials.java#L38-L39
This code says it should be done with Lapis.

**Comment by Draylar** [comment]
Thanks for the help, MelanX!
