### ISSUE TITLE
Crafting Table recipe...?

### ISSUE THREAD

**Issue by plaguewolf** [Draylar/vanilla-hammers#34]
for some reason, when i add you mod, it changes the vanilla crafting table recipe to require smooth stone and stick, like so:
Smooth Stone = S
Stick = St
Wood Planks = W
[St] [W]
[S]  [W]
whats up with that?

**Comment by lorilith** [comment]
libCD is outdated, can be fixed by installing the current libcd, changing to build with version 2.2.2, or both.
https://www.curseforge.com/minecraft/mc-mods/libcd
or 
`libcd_version=2.2.2+1.15.2` in gradle.properties

**Comment by Draylar** [comment]
Fixed in 1.7.1 for both 1.15 and 1.16 SNAPSHOT. Thanks!
