### ISSUE TITLE
add support for adabranium (nether things material mod) [Enhancement]

### ISSUE THREAD

**Issue by lorilith** [Draylar/vanilla-hammers#35]
Brandcraft_ released adabranium to have the vibranium (from nether things) and adamantium.
https://www.curseforge.com/minecraft/mc-mods/adabranium

any chance you could implement the vibranium hammer with a check for this mod as well as or instead of nether things, at least in 1.15? [and while you are at it, adamantium ;) ]

**Comment by Linguardium** [comment]
ping

**Comment by FaultyPixel** [comment]
I second this

**Comment by Draylar** [comment]
Added in [1.8.0](https://github.com/Draylar/vanilla-hammers/releases/tag/v1.8.0-1.15.2) thanks to Linguardium's PR. May look into adding the other material in the future (but I'm thinking of refactoring how other mods add hammers, so I'm holding off for now).
