### ISSUE TITLE
[1.14.4] Incompatibility with Fabric API 0.4.2

### ISSUE THREAD

**Issue by calrsg** [Draylar/vanilla-hammers#37]
Vanilla Hammers crashes on launch when using only Fabric API 0.4.2 and Vanilla Hammers 1.6.3. Launches properly using Fabric API 0.4.1. 
[crash-2020-02-14_01.38.06-client.txt](https://github.com/Draylar/vanilla-hammers/files/4199051/crash-2020-02-14_01.38.06-client.txt)

**Comment by Draylar** [comment]
Should[?] be fixed [here](https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers/files/2881305). Thanks Levo/Aqua for the help!
