### ISSUE TITLE
Crash on startup with 20w15a

### ISSUE THREAD

**Issue by Mantarri** [Draylar/vanilla-hammers#44]
The new build for 20w14a works fine on 20w14a, but crashes the game on startup when attempting to use it in 20w15a.
[Crash log](https://paste.ee/p/myMX7)

**Comment by Draylar** [comment]
Fixed with [this build](https://github.com/Draylar/vanilla-hammers/releases/tag/v1.7.3-20w15a). Thanks for the report!

**Comment by Mantarri** [comment]
No problem, I'll try to post here about anything strange, as I've been using this mod on my snapshot server.
