### ISSUE TITLE
Visual Bug

### ISSUE THREAD

**Issue by KXIIIS** [Draylar/vanilla-hammers#47]
It's not game breaking or anything but there's a visual bug when you hold the wooden hammer in your main hand. I'm on Fabric 0.8.2+build.194-1.15.2 using version vanilla-hammers-1.7.2_1.15.2

![Snip20200425_2](https://user-images.githubusercontent.com/62857357/80298369-78fe6b00-8759-11ea-9ccb-b46fd646c84f.png)

**Comment by Draylar** [comment]
I don't see any apparent visual bugs. What are you referring to in the image?

**Comment by KXIIIS** [comment]
The way the hammer is being held? Is it supposed to be like that?

**Comment by KXIIIS** [comment]
I'm sorry, I should've given more detail. Here's another picture to compare the one above to. 

![Snip20200426_1](https://user-images.githubusercontent.com/62857357/80316940-c832b300-87ce-11ea-8cf0-426dc194a817.png)

**Comment by Draylar** [comment]
Now I see it, haha. Thanks for the fix, Linguardium!
