### ISSUE TITLE
Fiery hammer balance issue

### ISSUE THREAD

**Issue by Angela** [Draylar/vanilla-hammers#51]
Not sure if this is intended, but in the course of using up a single fiery hammer, it always seems to drop two magma blocks, which is enough to just make another hammer when it breaks.

This means the only cost of having this hammer infinitely is sticks.

**Comment by Draylar** [comment]
I'm going to close this because I think it's mostly just coincidence rather than a bug with the tool (unless the Hammer is _actually dropping_ the Magma Blocks when it breaks). It seems like a similar argument could be made about going mining for Iron while using an Iron Hammer (correct me if I missed your point, of course). There's not a whole ton I could do besides tweaking the durability to use up faster (which I would be happy to do).

**Comment by Angela** [comment]
Hi @Draylar, I think I explained myself poorly. If I am using a fiery hammer to mine _anything_, just branch mining at y 12, every once in a while a magma block drops. With an unenchanted hammer, this seems to work out to about two blocks per one hammer once the durability gets to zero. Since the hammer replaces itself, it's basically infinite durability.

I assumed the hammer dropping blocks of its own material was a feature of the mod, but maybe not?

If I enchant the hammer with unbreaking/mending, magma blocks still drop while mining and now I have a strange new slow way to farm magma blocks 😬

If you don't think it's a problem, that's totally fine. Just wanted to make sure I was being clear about what I was seeing in case it was a bug.

**Comment by Angela** [comment]
Sorry, I just realized I was using a fork by MelanX (https://github.com/MelanX/vanilla-hammers) so I'm not even sure if this is relevant.

**Comment by Draylar** [comment]
Hahahaha, yeah, that would explain a lot. Here I was testing it in dev and going, _whaaaatt?_ MelanX's fork (the Forge version) is entirely separate, so I would report the issue over there. I don't have any features like that, but it might've been something they implemented (we don't have any feature parity, just the same name brand and textures). Good luck in your issue hunt!
