### ISSUE TITLE
Fiery Hammer should autosmelt

### ISSUE THREAD

**Issue by Draylar** [Draylar/vanilla-hammers#54]
Suggestion by AcidGames, Fiery Hammer should autosmelt while mining.

**Comment by dranorter** [comment]
That sounds pretty fun. It should work on materials like netherrack for which the hammer is the right tool, but not on sand.

This also makes me think the Fiery Hammer shouldn't be able to take the Silk Touch enchantment.

**Comment by Ayutac** [comment]
I agree that Autosmelt and Silk Touch are mutually exclusive.

**Comment by Draylar** [comment]
Autosmelting for the Fiery Hammer has been implemented (and you can't put Silk Touch on it).
