### ISSUE TITLE
Pickaxes can be enchanted with Curse of Gigantism but are not effected

### ISSUE THREAD

**Issue by Ayutac** [Draylar/vanilla-hammers#58]
Pickaxes can be enchanted with Curse of Gigantism but are not effected. This should be changed, either by adding an effect to the pickaxe (maybe a 2 height (ie. one down additionally) 1 width mining field for easier Tree Mining) or removing pickaxes from being able to receive the enchantment (via overriding Enchantment#isAcceptableItem).

**Comment by Draylar** [comment]
Thanks for the issue, just made it only applicable to hammers as you said.
