### ISSUE TITLE
Repair material for Lapis and Quartz

### ISSUE THREAD

**Issue by TimelapsedEon** [Draylar/vanilla-hammers#60]
I'm running the latest vanilla hammers v1.9.0-1.16.1 and neither lapis hammers nor quartz hammers can be repaired with materials. Additionally: Lapis can mine everything except ancient debris and Fiery's autosmelt is deactivated when holding shift.

**Comment by Draylar** [comment]
![image](https://user-images.githubusercontent.com/17728338/87735576-7e3ce600-c79b-11ea-9f2b-72c89435c17e.png)

Good catch, thanks for the report.  Fiery auto-smelting and the first issues have been fixed in 1.10.0.
