### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by CharaViolet** [Draylar/vanilla-hammers#66]
lauching the game with the mod causes the game to crash, and this is the resulting crash report:

> ```
> ---- Minecraft Crash Report ----
> // My bad.
> 
> Time: 7/25/20 8:02 AM
> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'vanilla-hammers'!
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
> 	at net.minecraft.class_310.<init>(class_310.java:425)
> 	at net.minecraft.client.main.Main.main(Main.java:177)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> Caused by: java.lang.NoClassDefFoundError: draylar/magna/item/HammerItem
> 	at com.github.draylar.vh.registry.Items.register(Items.java:75)
> 	at com.github.draylar.vh.registry.Items.<clinit>(Items.java:18)
> 	at com.github.draylar.vh.VanillaHammers.onInitialize(VanillaHammers.java:23)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$2143/1930135443.accept(Unknown Source)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
> 	... 11 more
> Caused by: java.lang.ClassNotFoundException: draylar.magna.item.HammerItem
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> 	... 16 more
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
> 	at net.minecraft.class_310.<init>(class_310.java:425)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.client.main.Main.main(Main.java:177)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.16.1
> 	Minecraft Version ID: 1.16.1
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 914462824 bytes (872 MB) / 2080374784 bytes (1984 MB) up to 2147483648 bytes (2048 MB)
> 	CPUs: 4
> 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
> 	Fabric Mods: 
> 		adorn: Adorn 1.9.1+1.16.1
> 		advancements-enlarger: Advancements Enlarger 0.2.2
> 		antighost: AntiGhost 1.16-fabric0.13.1-1.1.1
> 		appleskin: AppleSkin 1.0.11
> 		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
> 		beenfo: Beenfo 1.16-fabric0.13.1-1.0.3
> 		better-world-list: Better World List 1.0.3-1.16-pre8
> 		betterthanmending: BetterThanMending 1.1.1
> 		blue_endless_jankson: jankson +
> 		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
> 		cardinal-components-base: Cardinal Components API (base) 2.4.0-nightly.1.16-rc1.build.2
> 		cardinal-components-entity: Cardinal Components API (entities) 2.4.0-nightly.1.16-rc1.build.2
> 		cloth-basic-math: Cloth Basic Math 0.5.1
> 		cloth-client-events-v0: Cloth Client Events v0 1.0.4
> 		cloth-config2: Cloth Config v4 4.6.0
> 		convenient-mobgriefing: Convenient mobGriefing Gamerules 1.1.2
> 		cotton-client-commands: Cotton Client Commands 1.0.0+1.15.2
> 		couplings: Couplings 1.3.1
> 		dataloader: Data Loader 2.1.0+mc1.16.1
> 		decorative: Decorative 2.0.0 - Summer 2020 Update
> 		diggusmaximus: Diggus Maximus 1.3.0-1.16
> 		dishes: Delicious Dishes 1.0.3
> 		dungeons: JavaDungeons 1.2.1+1.16.1
> 		eggtab: Egg Tab 1.1.2+1.15-1.16
> 		extradoors: ExtraDoors 1.8.1-1.16
> 		fabric: Fabric API 0.14.0+build.371-1.16
> 		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
> 		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
> 		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
> 		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
> 		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
> 		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
> 		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
> 		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
> 		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
> 		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
> 		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
> 		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
> 		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
> 		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a977402
> 		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
> 		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
> 		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
> 		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea86602
> 		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
> 		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
> 		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
> 		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
> 		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f02
> 		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad602
> 		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
> 		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
> 		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
> 		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.2+4d66bed502
> 		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a6002
> 		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
> 		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
> 		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
> 		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
> 		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea86602
> 		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e02
> 		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
> 		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
> 		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e02
> 		fabricloader: Fabric Loader 0.8.8+build.202
> 		flora-doubling: Flora Doubling 1.1.1
> 		harvest: Harvest 1.2.12
> 		held-item-info: Held Item Info 1.1.2
> 		immersive_portals: Immersive Portals 0.20
> 		infinitevillagertrading: InfiniteVillagerTrading 1.16-fabric0.13.1-1.0.2
> 		infinityfix: Infinity Fix 1.1.0
> 		inventoryprofiles: Inventory Profiles 0.2.0
> 		jankson: Jankson 3.0.0+j1.2.0
> 		kirin: Kirin UI 1.6.4-1.16-rc1-1.16-SNAPSHOT
> 		kyrptconfig: Kytpt Config 1.1.0-1.16
> 		libcd: LibCapableData 2.5.0+1.16.1
> 		libgui: LibGui 2.0.1+1.16.1
> 		me_shedaniel_cloth_basic-math: basic-math 0.3.0
> 		minecraft: Minecraft 1.16.1
> 		mm: Manningham Mills 2.0
> 		modmenu: Mod Menu 1.12.2+build.17
> 		no-potion-offset: No Potion Offset 1.0.1-unstable
> 		noexpensive: NoExpensive 1.16.1-Fabric-1.1.3
> 		nomoreglowingpots: No More Glowing Pots 1.0.2
> 		onsoulfire: On Soul Fire r3
> 		optifabric: Optifabric 1.1.0-beta2
> 		org_jetbrains_annotations: annotations 17.0.0
> 		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
> 		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
> 		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
> 		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
> 		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
> 		org_slf4j_slf4j-api: slf4j-api 1.7.30
> 		org_slf4j_slf4j-simple: slf4j-simple 1.7.30
> 		org_zeroturnaround_zt-zip: zt-zip 1.14
> 		parchment: Parchment 1.0.2+1.15.2
> 		presencefootsteps: Presence Footsteps r26+1.16-rc1
> 		programmerartinjector: Programmer Art Injector 1.2.0
> 		reach-entity-attributes: Reach Entity Attribute 1.0.1
> 		roughlyenoughitems: Roughly Enough Items 4.10.2
> 		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
> 		smb: Better Mod Button 1.1.1
> 		sneak-through-berries: Sneak Through Berries 1.0.1
> 		stackablepotions: Stackable Potions 1.0.0
> 		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
> 		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
> 		survival-debug-stick: Survival Debug Stick 1.0.0
> 		trees-do-not-float: Trees Do Not Float 1.10.90
> 		trinkets: Trinkets 2.6.2
> 		vanilla-hammers: Vanilla Hammers 1.10.1-1.16.1
> 		voxelmap: VoxelMap 1.10.6
> 		waila: Hwyla 1.9.22
> 	Launched Version: fabric-loader-0.8.8+build.202-1.16.1
> 	Backend library: LWJGL version 3.2.2 build 10
> 	Backend API: NO CONTEXT
> 	GL Caps: 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	CPU: <unknown>
> 	OptiFine Version: OptiFine_1.16.1_HD_U_G2_pre3
> 	OptiFine Build: 20200710-182133
> 	Shaders: null
> 	OpenGlVersion: null
> 	OpenGlRenderer: null
> 	OpenGlVendor: null
> 	CpuCount: 0
> ```

**Comment by Draylar** [comment]
Can you try to update Fabric Loader (_not_ the API, the one you get through the exe installer or MultiMC) to the **latest** 9.0 version (not 8.0.x)?

**Comment by CharaViolet** [comment]
alright I'll try that (sorry for the late reply btw)

**Comment by CharaViolet** [comment]
It worked! thanks! And sorry for bothering lol

**Comment by Draylar** [comment]
Not a bother, took me a while to figure it out and had fun doing it. Still have no idea what the issue was, but the solution works, lol
