### ISSUE TITLE
Found a texture-missing test diamond hammer

### ISSUE THREAD

**Issue by linzexin022** [Draylar/vanilla-hammers#68]
![image](https://user-images.githubusercontent.com/59003232/88786736-77639980-d1c5-11ea-8357-02846275502e.png)

**Comment by linzexin022** [comment]
I also found that I couldn't break any blocks except stones and ore unless I was sneaking.

**Comment by Draylar** [comment]
Both issues have been fixed in 2.0.2. Thanks for the report!

**Comment by Draylar** [comment]
okay, I forgot to remove the file in 2.0.2
