### ISSUE TITLE
Error in Log: test:diamond_hammer

### ISSUE THREAD

**Issue by rxay579** [Draylar/vanilla-hammers#69]
From my client's log:
[Worker-Main-10/WARN]: Unable to load model: 'test:diamond_hammer#inventory' referenced from: test:diamond_hammer#inventory: java.io.FileNotFoundException: test:models/item/diamond_hammer.json

Also shows up in REI and creative inventory.

Looks like a testing leftover.  Doesn't seem to break anything that I can easily tell.

**Comment by Draylar** [comment]
Fixed in 2.0.3, thanks.
