### ISSUE TITLE
Feature request: Please add 1x1 hitbox option to hammers.

### ISSUE THREAD

**Issue by calloatti** [Draylar/vanilla-hammers#7]
Please add 1x1 hitbox option to hammers, just like the pick has. Thanks!

**Comment by ChloeDawn** [comment]
I'd suggest a config for disabled/enabled/sneaking. With the 3rd option being "use 1x1 targetting when the miner is sneaking"

**Comment by Draylar** [comment]
Forgot to close this; fixed in 1.3.2.
