### ISSUE TITLE
Missing embedded dependencies on CurseForge

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Draylar/vanilla-hammers#71]
It looks like this embeds some dependencies but doesn't list any on CurseForge. This made it hard for a user of my Anvil Crushing Recipes mod to track down a conflict. Please add dependencies to CurseForge to make it easier to find mod interactions.

**Comment by Draylar** [comment]
Done, thanks.

**Comment by supersaiyansubtlety** [comment]
thanks
