### ISSUE TITLE
Netherite Hammer not supporting Silk Touch Enchantment

### ISSUE THREAD

**Issue by Ropirela29** [Draylar/vanilla-hammers#73]
Netherite Hammer doesn't support silk touch, tried with a book on an anvil, and with a command, didn't work. Says, "item.vanilla-hammers.netherite_hammer cannot support that enchantment. I will be looking forward this fix. Thx.

**Comment by Draylar** [comment]
Had `item.getData().canSmelt();` instead of `!item.getData().canSmelt();` to check whether a Hammer is compatible with Silk Touch. Oops! Fixed in 2.0.6, thanks for the report.
