### ISSUE TITLE
Can't apply silktouch to emerald hammer via Anvil

### ISSUE THREAD

**Issue by KrisCris** [Draylar/vanilla-hammers#77]
I cannot apply silk touch to emerald hammer by anvil & enchantment book, is this intended?
Btw, can you please make a list of enchantments available for hammers?

**Comment by Draylar** [comment]
The Silk Touch issue was fixed in one of the 1.16.2 versions, iirc. Available enchantments are the exact same as Pickaxes, with the addition of the Curse of Gigantism.

**Comment by KrisCris** [comment]
Oh... I am sorry, I thought I have downloaded the latest version.
