### ISSUE TITLE
[1.16.2 versions] Conflict With Vanilla Hammers and Tech Reborn

### ISSUE THREAD

**Issue by KingShibaInu** [Draylar/vanilla-hammers#79]
The game crashes with just the two mods installed; The crash report is below.
[crash-2020-09-05_20.41.29-client.txt](https://github.com/Draylar/vanilla-hammers/files/5178998/crash-2020-09-05_20.41.29-client.txt)

**Comment by Draylar** [comment]
TechReborn is pulling an old version of LibCD. I'm pulling the new 1.16.2 version which removed a few features, they're using the [1.15.2 version](https://github.com/TechReborn/TechReborn/blob/82c07220664586c248542e70da2ae5e85bb249e9/build.gradle#L84).

**Comment by KingShibaInu** [comment]
Okay, let the Tech Reborn team of the issue as well. Thank you for getting back so fast.
