### ISSUE TITLE
Recipe documentation

### ISSUE THREAD

**Issue by Draylar** [Draylar/vanilla-hammers#8]
Default recipes should be documented on the wiki and CurseForge page, ideally in the same format as the introductory image on the CF page.

**Comment by lemmonsm** [comment]
Seconded. I have no idea how to make these hammers and may switch to another mod just because of bad documentation.

**Comment by ghost** [comment]
Perhaps you should add some recipe advancements so that players can unlock relvant recipes e.g.obtaining a diamond unlocks diamond hammer recipe.

**Comment by Levoment** [comment]
I could do this. Does anyone know the used font in the introductory image on CF page? Or can I use any font? 

The advancement part doesn't sound like a bad idea either. I was testing adding custom advancements and the default hammer recipes get added on the Recipe Book as we gather materials in the game. We just have to define what would cause the recipe to be unlocked/added in the book.

**Comment by Levoment** [comment]
I made images with the recipes and also cloned the Wiki to add the images to it. But since the wiki is not part of the project, I don't know how to submit my additions for review.

**Comment by sshine** [comment]
@Draylar: How would you recommend that recipes are documented?

It seems that @Levoment already made the image art.

I came looking for recipes and thought "maybe it's easiest to just look in the source code", but found this issue when searching.

For those who do not dare decipher recipes from source code, maybe @Levoment's images could be super helpful?

The "skill tree" image on https://www.curseforge.com/minecraft/mc-mods/vanilla-hammers (in particlular, [this image](https://i.imgur.com/8bILtNw.png)) is a bit of a conundrum to me. If I were more experienced with Minecraft, I might have known that you're using a particular mod, but it doesn't say which. Either way, I can't find this overview in-game.

**Comment by sshine** [comment]
@Levoment: Maybe if you drop the images in this issue, @Draylar or someone else can embed them elsewhere as well?

**Comment by Draylar** [comment]
Side note: I would recommend using [Roughly Enough Items](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) to view recipes in-game.

I could add recipe advancements so they are in the recipe book, and I'd also be fine with adding recipe images on the CF page (I just need to make them, or use Levo's). 

*_The recipes are just datapacks (no code involved), but they still aren't user-friendly for reading._

**Comment by Levoment** [comment]
The image I made is for an old version. It doesn't include a Netherite Hammer. But I'll attach it here. I also added the recipes to the Vanilla Minecraft recipe book for an older version of the mod using advancements, but never made a pull request and I think I deleted the whole project folder accidentally when moving computers. (and I didn't push it to my fork). If you open the image in a new tab, you can zoom.
![Hammer Recipes](https://user-images.githubusercontent.com/30224138/76710972-be029c80-66d9-11ea-9bd1-efc05e73b789.png)

**Comment by Levoment** [comment]
I just added the recipes to the wiki of my fork, but I see no option to make a pull requests. It looks like GitHub doesn't support pull requests on wikis. [This question's answer](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) is from 2012, but it looks like it is still the case today.

A workaround could be: https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html

Although it seems a little complex.

My wiki is on: https://github.com/Levoment/vanilla-hammers/wiki

**Comment by Draylar** [comment]
I've added the (awesome) recipe image to the CurseForge images page (if that's alright with you; gave credit in the description). 

Wish PRing to wikis was possible... sad times.

**Comment by Levoment** [comment]
Sure, no problem. I made it to be used. If needed to be used elsewhere, it can be used without attribution to me. I don't mind at all since it's just screenshots glued together on the original image with the pictures of the hammers. :)
