### ISSUE TITLE
[1.16.4] Can't apply Efficiency IV via anvil

### ISSUE THREAD

**Issue by BHY4A** [Draylar/vanilla-hammers#81]
When I'm trying to apply Efficiency IV to Emerald Hammer that already enchanted with Efficiency IV game crashes

Log: https://pastebin.com/jE65MkpM

**Comment by James103** [comment]
1. Can you reproduce this crash in a testing environment (test world)?
2. Does a similar crash get produced when you do this with Efficiency V + Efficiency III (or any other lower level)?
3. Does a similar crash get produced when you do this with Fortune II + Fortune II?

**Comment by BHY4A** [comment]
> 
> 
>     1. Can you reproduce this crash in a testing environment (test world)?
> 
>     2. Does a similar crash get produced when you do this with Efficiency V + Efficiency III (or any other lower level)?
> 
>     3. Does a similar crash get produced when you do this with Fortune II + Fortune II?

I've noticed that it happens with any item in 2nd slot. I have Netherite Plus mod that adds Netherite Anvil and NP's anvil works normally, Idk why.
So, I think the trouble isn't in your's mod.

**Comment by James103** [comment]
Have you tried reproducing this with other Hammers (including unenchanted Hammers)?

**Comment by Draylar** [comment]
Thanks for the help, James! The "offending" mod (not their fault either) here is [NoExpensive](https://www.curseforge.com/minecraft/mc-mods/noexpensive), not Vanilla Hammers:
   - `method_31549` (`player.getAbilities()`) only exists on 1.17 snapshots
   - NoExpensive is one of the only mods on your list that is in snapshots
   - [boom](https://github.com/Enaium-FabricMC/NoExpensive/blob/933238ebfe701bbb91073e1b14dd0589cb373127/src/main/java/cn/enaium/noexpensive/mixin/AnvilScreenHandlerMixin.java#L134)
  
You can't use 1.17 snapshot mods on 1.16.4. Downgrade NoExpensive ([or switch to a mod that doesn't override the entire anvil result method](https://github.com/Enaium-FabricMC/NoExpensive/blob/933238ebfe701bbb91073e1b14dd0589cb373127/src/main/java/cn/enaium/noexpensive/mixin/AnvilScreenHandlerMixin.java#L50)).
