### ISSUE TITLE
Wiki: Netherite hammer isn't included in "Tool Stats"

### ISSUE THREAD

**Issue by James103** [Draylar/vanilla-hammers#82]
Between "Diamond" and "Emerald", there should be the following:
> Netherite:
> * Speed: 9
> * Durability: 2031
> * Enchantability: 15
> * Mining Level: 4

**Comment by Draylar** [comment]
Netherite has been added to the wiki now, thanks for letting me know! I also updated all the material speeds to reflect their true mining speeds (previously, it was speed / 3.5f).
