### ISSUE TITLE
Suggestion: Config option to change the speed of hammers

### ISSUE THREAD

**Issue by James103** [Draylar/vanilla-hammers#83]
> I also updated all the material speeds to reflect their true mining speeds (previously, it was speed / 3.5f)

Would it be possible to add a config option to change the multiplier on the mining speed for hammers?
Bonus: What about including a config option for the speed multiplier for Curse of Gigantism (default `0.2f`)?

**Comment by Draylar** [comment]
Next update will have a universal speed config option (`breakSpeedMultiplier`); 0.5 would be 50% speed, and 1.0 (default) is normal speed. 

Curse of Gigantism is now in Magna, so I'm moving the issue [here](https://github.com/Draylar/magna/issues/13).
