### ISSUE TITLE
Emerald Hammer balance issue

### ISSUE THREAD

**Issue by Cooliosity** [Draylar/vanilla-hammers#84]
Today I have noticed that the emerald hammer is completely unbalanced. Emeralds are obtained by trading with villagers and since the emerald trades are super cheap, the emerald hammer is essentially free. On top of being almost free of cost, the emerald hammer has insanely high enchantability (higher than gold!) and is only 0.1 slower than the gold hammer. It also has 32x the durability of the gold hammer. The emerald hammer also has the same mining level as diamond (level 3), while gold has the mining level of wood (level 0). Now that you know that the emerald hammer is essentially a better gold hammer, while also being cheaper (emeralds are almost worthless since villagers are a thing), lets compare the emerald hammer to the diamond hammer. The emerald hammer is faster and has higher enchantability than the diamond hammer and the only disadvantage it has is it's inferior durability. This is completely neglectable since you can easily obtain a mending book from a villager. I think that the emerald hammer should be rebalanced to reflect it's cost. In my opinion it should have lower speed than diamond (maybe 1.7 like iron?) and low enchantability. I don't think that the emerald hammer should be the best hammer in the game, since it's so easy to obtain. You could of course argue that the netherite hammer is better because it has a higher mining level, but that's completely irrelevant since the game has no blocks that you can't mine with a diamond pickaxe (except of course bedrock and other blocks that are unobtainable).

**Comment by Draylar** [comment]
Thank you for the feedback. In the next update, the Emerald Hammer will have the following stat changes:
```
Durability: 1028 -> 750
Mining Speed: 3.4 -> 2.0
Attack Damage: 11 -> 7
Enchantability: 25 -> 10
```
This mining speed is directly between Iron and Diamond. The attack damage is +2 over Iron (although that's mostly irrelevant for hammers), and the enchantability has been drastically lowered. The durability has also been nerfed by 25%.

I think the role of the Emerald hammer at this point is to be a level-3 mining level tool with stats in-between Iron and Diamond. If anyone has additional feedback on these nerfs or extra ideas, we can test them out in the next release. I think this is a good compromise that does not make the Emerald hammer entirely useless over Iron. 

Thanks again for the suggestions!
