### ISSUE TITLE
Does not Work Outside Vanilla Reach Range

### ISSUE THREAD

**Issue by milkev** [Draylar/vanilla-hammers#85]
Hammers (and excavators) dont mine blocks, unless crouched, while the players reach range has been increased. Such as through reach-attribute, or a mod like BeaconOverhaul.
*dont mine blocks outside vanilla reach range, works as expected within vanilla reach.

**Comment by Computerlabrat** [comment]
I was going to mention this issue with the Pehkui mod's player scaling capabilities, which is useful to extend your reach when you increase your size. It seems you beat me to it, though. Would be more useful for creative mode if this wasn't an issue. I hope they fix it.

**Comment by Draylar** [comment]
Oh, I fixed this in Magna but forgot to push a VH update with it. For now, you should be able to install the [latest version of Magna](https://github.com/Draylar/magna/releases/tag/1.5.1-1.16.5) manually (place it in your mods folder like a normal mod).
