### ISSUE TITLE
Update/Format Wiki

### ISSUE THREAD

**Issue by Wdavery** [Draylar/vanilla-hammers#93]
Doesn't look like its possible to PR the wiki but I did a quick reformatting to make it easier to read for my own use, thought it may make it easier for others as well (and perhaps useful to copy over to the empty Vanilla Excavators wiki) 

Preview:
--- 

By default, the durability modifier is 5. To get the final durability of an item, multiply the durability stat by the modifier.

### Hammers 
Name | Speed | Durability | Enchantability | Mining Level
:---:|:---:|:---:|:---:|:---:|
Wood Hammer | 0.57 | 59 | 15 | 0
Stone Hammer | 1.15 | 131 | 5 | 1
Iron Hammer | 1.7 | 250 | 14 | 2
Gold Hammer | 3.5 | 32 | 22 | 0
Diamond Hammer | 2.3 | 1561 | 10 | 3
Netherite Hammer | 2.6 | 2031 | 15 | 4
Emerald Hammer | 3.4 | 1028 | 25 | 3
Obsidian Hammer | 1.4 | 2048 | 5 | 2
Lapis Hammer | 1.7 | 220 | 30 | 1
Quartz Hammer | 2.3 | 1028 | 10 | 2
Fiery Hammer | 2 | 750 | 15 | 3
Prismarine Hammer | 3.4 | 750 | 20 | 3
Ender Hammer | 2.85 | 1561 | 10 | 3
Slime Hammer | 1.7 | 1500 | 20 | 2

Raw Markdown:
---
```
By default, the durability modifier is 5. To get the final durability of an item, multiply the durability stat by the modifier.

### Hammers 
Name | Speed | Durability | Enchantability | Mining Level
:---:|:---:|:---:|:---:|:---:|
Wood Hammer | 0.57 | 59 | 15 | 0
Stone Hammer | 1.15 | 131 | 5 | 1
Iron Hammer | 1.7 | 250 | 14 | 2
Gold Hammer | 3.5 | 32 | 22 | 0
Diamond Hammer | 2.3 | 1561 | 10 | 3
Netherite Hammer | 2.6 | 2031 | 15 | 4
Emerald Hammer | 3.4 | 1028 | 25 | 3
Obsidian Hammer | 1.4 | 2048 | 5 | 2
Lapis Hammer | 1.7 | 220 | 30 | 1
Quartz Hammer | 2.3 | 1028 | 10 | 2
Fiery Hammer | 2 | 750 | 15 | 3
Prismarine Hammer | 3.4 | 750 | 20 | 3
Ender Hammer | 2.85 | 1561 | 10 | 3
Slime Hammer | 1.7 | 1500 | 20 | 2
```

**Comment by Draylar** [comment]
Super helpful, thank you so much! Just updated the wiki with your table. Much appreciated.
