### ISSUE TITLE
I was told to report this because I was not supposed to see it.

### ISSUE THREAD

**Issue by notmaroun** [Draylar/vanilla-hammers#99]
![image](https://user-images.githubusercontent.com/80657566/132085775-dd43d529-0489-4897-868b-fa122fa6cf3d.png)

**Comment by dranorter** [comment]
Are you using a mod which tracks how many blocks a pickaxe/hammer has broken total?

If so, I think the "please report this" text is coming from the mod which provided the "Pipe Block".

**Comment by notmaroun** [comment]
This makes sense! The mod is called Spellbound I think, the mod is called Rock Collecting and I suppose Pipe Blocks are a type of rock. Sorry for the trouble!
